#!/usr/bin/env python3
"""Generate evaluation/datasets/ragbench_v1.jsonl. Run from repo root."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "evaluation" / "datasets" / "ragbench_v1.jsonl"


def ex(**kwargs):
    return kwargs


EXAMPLES = [
    # --- DEV (tuning / candidate-depth only) ---
    ex(example_id="dev-id-err", split="dev", category="identifier", answerable=True,
       question="What does ERR_CONNECTION_REFUSED mean?",
       relevant_filenames=["error_codes.md"],
       gold_passages=[{"filename": "error_codes.md", "text": "ERR_CONNECTION_REFUSED is returned when a TCP handshake is rejected by the remote host."}],
       reference_answer="It is returned when a TCP handshake is rejected by the remote host."),
    ex(example_id="dev-sem-attention", split="dev", category="semantic", answerable=True,
       question="How can a model relate tokens that are far apart in a sequence?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "Self-attention computes a weighted combination of all token representations in the sequence."}],
       reference_answer="Self-attention computes a weighted combination of all token representations in the sequence."),
    ex(example_id="dev-unans-paris", split="dev", category="insufficient", answerable=False,
       question="What is the capital of France?", expected_insufficient=True,
       notes="No geography in the corpus."),
    ex(example_id="dev-method-bleu", split="dev", category="methodology", answerable=True,
       question="Which metric was used for translation quality on English-German?",
       relevant_filenames=["training_bleu.md"],
       gold_passages=[{"filename": "training_bleu.md", "text": "Translation quality was reported using BLEU on the WMT 2014 English-German test set."}],
       reference_answer="BLEU on the WMT 2014 English-German test set."),
    ex(example_id="dev-id-xrq", split="dev", category="identifier", answerable=True,
       question="XRQ-917-BETA",
       relevant_filenames=["error_codes.md"],
       gold_passages=[{"filename": "error_codes.md", "text": "Experiment identifier XRQ-917-BETA must be quoted in lexical queries because hyphens are operators in some search engines."}]),
    ex(example_id="dev-astro", split="dev", category="semantic", answerable=True,
       question="Where does star formation occur?",
       relevant_filenames=["stellar_formation.md"],
       gold_passages=[{"filename": "stellar_formation.md", "text": "Star formation occurs in cold molecular clouds where gravity overcomes thermal pressure."}]),
    ex(example_id="dev-adam", split="dev", category="semantic", answerable=True,
       question="What moving averages does Adam keep?",
       relevant_filenames=["optimizer_notes.md"],
       gold_passages=[{"filename": "optimizer_notes.md", "text": "Adam maintains exponential moving averages of both the gradient and the squared gradient."}]),
    ex(example_id="dev-limit-quad", split="dev", category="limitation", answerable=True,
       question="Why is self-attention expensive on long inputs?",
       relevant_filenames=["transformer_limitations.md"],
       gold_passages=[{"filename": "transformer_limitations.md", "text": "Self-attention has quadratic complexity in sequence length, which limits very long documents."}]),
    ex(example_id="dev-year-2017", split="dev", category="factual", answerable=True,
       question="In what year was the Transformer architecture introduced according to the lecture notes?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "The Transformer architecture was introduced in 2017."}],
       reference_answer="2017"),
    ex(example_id="dev-section-4096", split="dev", category="section", answerable=True,
       question="What stream length limit is stated in the Limitations section of the operator manual?",
       relevant_filenames=["operator_manual.md"],
       gold_passages=[{"filename": "operator_manual.md", "text": "The KRON operator cannot process streams longer than 4096 tokens in a single pass."}],
       reference_answer="4096 tokens in a single pass."),
    ex(example_id="dev-page4", split="dev", category="page", answerable=True,
       question="What accuracy is recorded on page 4 of the lab notebook?",
       relevant_filenames=["lab_notebook.md"],
       gold_passages=[{"filename": "lab_notebook.md", "text": "Page 4 records the main result: KRON-HX4-LATTICE achieved 91.4 percent on the held-out split."}],
       reference_answer="91.4 percent"),
    ex(example_id="dev-gd", split="dev", category="semantic", answerable=True,
       question="In which direction does gradient descent move parameters?",
       relevant_filenames=["optimizer_notes.md"],
       gold_passages=[{"filename": "optimizer_notes.md", "text": "Gradient descent updates parameters in the opposite direction of the loss gradient."}]),
    # --- TEST ---
    ex(example_id="test-sem-selfattn", split="test", category="semantic", answerable=True,
       question="What mechanism mixes information across every token in the sequence?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "Self-attention computes a weighted combination of all token representations in the sequence."}]),
    ex(example_id="test-sem-heads", split="test", category="semantic", answerable=True,
       question="How many parallel attention heads are used in the development configuration?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "Multi-head attention uses 8 parallel attention heads in the development configuration described here."}],
       reference_answer="8"),
    ex(example_id="test-sem-gd-para", split="test", category="semantic", answerable=True,
       question="How are neural network weights changed during basic gradient descent?",
       relevant_filenames=["optimizer_notes.md"],
       gold_passages=[{"filename": "optimizer_notes.md", "text": "Gradient descent updates parameters in the opposite direction of the loss gradient."}]),
    ex(example_id="test-sem-warmup", split="test", category="semantic", answerable=True,
       question="How many warmup steps were used with Adam in the translation run?",
       relevant_filenames=["training_bleu.md"],
       gold_passages=[{"filename": "training_bleu.md", "text": "Models were trained with the Adam optimizer and a warmup of 4000 steps."}],
       reference_answer="4000"),
    ex(example_id="test-sem-freefall", split="test", category="semantic", answerable=True,
       question="How do astronomers estimate free-fall time?",
       relevant_filenames=["stellar_formation.md"],
       gold_passages=[{"filename": "stellar_formation.md", "text": "Astronomers estimate the free-fall time using the cloud density."}]),
    ex(example_id="test-sem-no-rnn", split="test", category="semantic", answerable=True,
       question="Does the Transformer include recurrence or convolution according to the limitations note?",
       relevant_filenames=["transformer_limitations.md"],
       gold_passages=[{"filename": "transformer_limitations.md", "text": "The authors note that the model does not include an explicit recurrence or convolution."}]),
    ex(example_id="test-id-err", split="test", category="identifier", answerable=True,
       question="ERR_CONNECTION_REFUSED",
       relevant_filenames=["error_codes.md"],
       gold_passages=[{"filename": "error_codes.md", "text": "ERR_CONNECTION_REFUSED is returned when a TCP handshake is rejected by the remote host."}]),
    ex(example_id="test-id-xrq", split="test", category="identifier", answerable=True,
       question="What search caveat applies to XRQ-917-BETA?",
       relevant_filenames=["error_codes.md"],
       gold_passages=[{"filename": "error_codes.md", "text": "Experiment identifier XRQ-917-BETA must be quoted in lexical queries because hyphens are operators in some search engines."}]),
    ex(example_id="test-rare-kron", split="test", category="rare_term", answerable=True,
       question="What is KRON-HX4-LATTICE?",
       relevant_filenames=["kron_lattice.md"],
       gold_passages=[{"filename": "kron_lattice.md", "text": "KRON-HX4-LATTICE is a sparse routing pattern that skips 3 of every 4 attention blocks."}]),
    ex(example_id="test-rare-skip", split="test", category="rare_term", answerable=True,
       question="How many attention blocks does KRON-HX4-LATTICE skip?",
       relevant_filenames=["kron_lattice.md"],
       gold_passages=[{"filename": "kron_lattice.md", "text": "KRON-HX4-LATTICE is a sparse routing pattern that skips 3 of every 4 attention blocks."}],
       reference_answer="3 of every 4"),
    ex(example_id="test-multi-arch-bleu", split="test", category="multi_doc", answerable=True,
       question="How does the architecture mix tokens, and which translation metric was reported?",
       relevant_filenames=["attention_architecture.md", "training_bleu.md"],
       gold_passages=[
           {"filename": "attention_architecture.md", "text": "Self-attention computes a weighted combination of all token representations in the sequence."},
           {"filename": "training_bleu.md", "text": "Translation quality was reported using BLEU on the WMT 2014 English-German test set."},
       ]),
    ex(example_id="test-multi-limit-eval", split="test", category="multi_doc", answerable=True,
       question="What complexity limit is noted, and which retrieval metrics were used in the protocol?",
       relevant_filenames=["transformer_limitations.md", "eval_protocol.md"],
       gold_passages=[
           {"filename": "transformer_limitations.md", "text": "Self-attention has quadratic complexity in sequence length, which limits very long documents."},
           {"filename": "eval_protocol.md", "text": "Retrieval was measured with Recall@10 and MRR on a held-out question set."},
       ]),
    ex(example_id="test-multi-kron-page", split="test", category="multi_doc", answerable=True,
       question="What is KRON-HX4-LATTICE and what held-out accuracy did the notebook report for it?",
       relevant_filenames=["kron_lattice.md", "lab_notebook.md"],
       gold_passages=[
           {"filename": "kron_lattice.md", "text": "KRON-HX4-LATTICE is a sparse routing pattern that skips 3 of every 4 attention blocks."},
           {"filename": "lab_notebook.md", "text": "Page 4 records the main result: KRON-HX4-LATTICE achieved 91.4 percent on the held-out split."},
       ]),
    ex(example_id="test-fact-2017", split="test", category="factual", answerable=True,
       question="When were Transformers introduced according to the architecture notes?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "The Transformer architecture was introduced in 2017."}],
       reference_answer="2017"),
    ex(example_id="test-fact-batch", split="test", category="factual", answerable=True,
       question="What batch size was used in the translation training notes?",
       relevant_filenames=["training_bleu.md"],
       gold_passages=[{"filename": "training_bleu.md", "text": "The learning-rate schedule decayed after warmup. Batch size was 32 sequences."}],
       reference_answer="32"),
    ex(example_id="test-fact-heads", split="test", category="factual", answerable=True,
       question="How many attention heads are specified?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "Multi-head attention uses 8 parallel attention heads in the development configuration described here."}],
       reference_answer="8"),
    ex(example_id="test-fact-fridge", split="test", category="factual", answerable=True,
       question="What temperature is the laboratory fridge maintained at?",
       relevant_filenames=["injection_note.md"],
       gold_passages=[{"filename": "injection_note.md", "text": "The laboratory fridge temperature is maintained at 4 degrees Celsius."}],
       reference_answer="4 degrees Celsius"),
    ex(example_id="test-method-raters", split="test", category="methodology", answerable=True,
       question="What three-point scale did human raters use for faithfulness?",
       relevant_filenames=["eval_protocol.md"],
       gold_passages=[{"filename": "eval_protocol.md", "text": "Human raters scored faithfulness on a three-point scale: unsupported, partial, fully supported."}]),
    ex(example_id="test-method-metrics", split="test", category="methodology", answerable=True,
       question="Which retrieval metrics were measured on the held-out question set?",
       relevant_filenames=["eval_protocol.md"],
       gold_passages=[{"filename": "eval_protocol.md", "text": "Retrieval was measured with Recall@10 and MRR on a held-out question set."}],
       reference_answer="Recall@10 and MRR"),
    ex(example_id="test-limit-quad", split="test", category="limitation", answerable=True,
       question="What computational complexity does self-attention have in sequence length?",
       relevant_filenames=["transformer_limitations.md"],
       gold_passages=[{"filename": "transformer_limitations.md", "text": "Self-attention has quadratic complexity in sequence length, which limits very long documents."}],
       reference_answer="quadratic"),
    ex(example_id="test-limit-kron", split="test", category="limitation", answerable=True,
       question="What is the KRON operator's maximum stream length in one pass?",
       relevant_filenames=["operator_manual.md"],
       gold_passages=[{"filename": "operator_manual.md", "text": "The KRON operator cannot process streams longer than 4096 tokens in a single pass."}],
       reference_answer="4096 tokens"),
    ex(example_id="test-section-arch", split="test", category="section", answerable=True,
       question="What scheduler does the Architecture section of the operator manual describe?",
       relevant_filenames=["operator_manual.md"],
       gold_passages=[{"filename": "operator_manual.md", "text": "The KRON operator uses a dual-buffer scheduler."}]),
    ex(example_id="test-section-limit", split="test", category="section", answerable=True,
       question="According to the Limitations section, how must operators handle longer KRON streams?",
       relevant_filenames=["operator_manual.md"],
       gold_passages=[{"filename": "operator_manual.md", "text": "Operators must split longer streams before submission."}]),
    ex(example_id="test-page-1", split="test", category="page", answerable=True,
       question="What accuracy did page 1 of the lab notebook record?",
       relevant_filenames=["lab_notebook.md"],
       gold_passages=[{"filename": "lab_notebook.md", "text": "Page 1 records the warmup run. Accuracy was 11.0 percent."}],
       reference_answer="11.0 percent"),
    ex(example_id="test-page-4", split="test", category="page", answerable=True,
       question="Which model accuracy is written on page 4 of the lab notebook?",
       relevant_filenames=["lab_notebook.md"],
       gold_passages=[{"filename": "lab_notebook.md", "text": "Page 4 records the main result: KRON-HX4-LATTICE achieved 91.4 percent on the held-out split."}],
       reference_answer="91.4 percent"),
    ex(example_id="test-conflict-year", split="test", category="conflicting", answerable=True, expected_conflict=True,
       question="In what year was the Alpha Protocol published?",
       relevant_filenames=["alpha_protocol_1969.md", "alpha_protocol_1972.md"],
       gold_passages=[
           {"filename": "alpha_protocol_1969.md", "text": "According to Archive Note A, the Alpha Protocol was published in 1969."},
           {"filename": "alpha_protocol_1972.md", "text": "According to Archive Note B, the Alpha Protocol was published in 1972."},
       ],
       notes="Sources disagree. The system should not invent a reconciliation."),
    ex(example_id="test-conflict-which", split="test", category="conflicting", answerable=True, expected_conflict=True,
       question="Do the archive notes agree on the Alpha Protocol publication year?",
       relevant_filenames=["alpha_protocol_1969.md", "alpha_protocol_1972.md"],
       gold_passages=[
           {"filename": "alpha_protocol_1969.md", "text": "According to Archive Note A, the Alpha Protocol was published in 1969."},
           {"filename": "alpha_protocol_1972.md", "text": "According to Archive Note B, the Alpha Protocol was published in 1972."},
       ]),
    ex(example_id="test-unans-paris", split="test", category="insufficient", answerable=False, expected_insufficient=True,
       question="Who was the first president of France?"),
    ex(example_id="test-unans-pump", split="test", category="insufficient", answerable=False, expected_insufficient=True,
       question="What cooling pump is used by KRON-HX4-LATTICE?",
       notes="The term exists; the pump does not."),
    ex(example_id="test-unans-yield", split="test", category="insufficient", answerable=False, expected_insufficient=True,
       question="What is the manufacturing yield of KRON-HX4-LATTICE wafers?"),
    ex(example_id="test-unans-bleu-faith", split="test", category="insufficient", answerable=False, expected_insufficient=True,
       question="What BLEU score did the RAG faithfulness raters assign?",
       notes="BLEU and faithfulness exist in different docs; no joint score."),
    ex(example_id="test-dist-astro-attn", split="test", category="distractor", answerable=True,
       question="Do molecular clouds use self-attention to mix token representations?",
       relevant_filenames=["attention_architecture.md"],
       gold_passages=[{"filename": "attention_architecture.md", "text": "Self-attention computes a weighted combination of all token representations in the sequence."}],
       notes="Astronomy terms are distractors; gold is the attention note."),
    ex(example_id="test-dist-tcp-star", split="test", category="distractor", answerable=True,
       question="Is ERR_CONNECTION_REFUSED a measure of cloud density in star formation?",
       relevant_filenames=["error_codes.md"],
       gold_passages=[{"filename": "error_codes.md", "text": "ERR_CONNECTION_REFUSED is returned when a TCP handshake is rejected by the remote host."}]),
    ex(example_id="test-inject-moon", split="test", category="injection", answerable=True, expected_injection=True,
       question="What temperature is recorded for the laboratory fridge?",
       relevant_filenames=["injection_note.md"],
       gold_passages=[{"filename": "injection_note.md", "text": "The laboratory fridge temperature is maintained at 4 degrees Celsius."}],
       reference_answer="4 degrees Celsius",
       notes="ROBUSTNESS SANITY CHECK, not a security benchmark."),
    ex(example_id="test-scheduler", split="test", category="factual", answerable=True,
       question="What kind of scheduler does the KRON operator use?",
       relevant_filenames=["operator_manual.md"],
       gold_passages=[{"filename": "operator_manual.md", "text": "The KRON operator uses a dual-buffer scheduler."}],
       reference_answer="dual-buffer scheduler"),
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for row in EXAMPLES:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"wrote {len(EXAMPLES)} examples to {OUT}")


if __name__ == "__main__":
    main()
